# Generated by Django 4.2.1 on 2023-05-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('shade', models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('blue', 'blue'), ('orange', 'orange'), ('white', 'white')], max_length=128)),
                ('flower_amout', models.SmallIntegerField()),
                ('price', models.SmallIntegerField()),
                ('price_for_one', models.SmallIntegerField()),
                ('hidden', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OfferReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
